[PORTS]
# Part of the interface name for standard MIDI messages
interface_1_keyword = Standard MIDI
# Part of the interface name for CQ18T messages
interface_2_keyword = CQ18T

[FILTERS]
# Global filter options for both interfaces (must be 'yes' or 'no')
# Note: Sysex is ENABLED by default for Interface 1 in the logic below,
#       but this setting can be used to override it if desired.

record_midi_clock = no
record_active_sensing = no
record_sysex = yes